services:
  # Backend Web Service
  - type: web
    name: streaming-platform-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: streaming-platform-backend
          property: port

  # Frontend Static Site  
  - type: web
    name: streaming-platform-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: streaming-platform-backend
          property: host
        
databases:
  # No database needed for this project